/**
 * Yang Beauty Salon — Full VI manual pipeline (CLI)
 * 
 * 1. Brand DNA extraction (DeepSeek)
 * 2. Scene image generation (ComfyUI x5)
 * 3. PPTX rendering (render-pptx)
 * 
 * Run: npx tsx yang_manual.ts
 */
import "dotenv/config";
import path from "path";
import { writeFile } from "fs/promises";
import { renderPptxToBuffer } from "./src/lib/pptx/render-pptx";
import { getIndustryType } from "./src/lib/brand/industry-types";
import { getIndustryKnowledge } from "./src/lib/brand/industry-knowledge";

// ── Yang's Beauty Salon Profile ─────────────────────────

const brandProfile = {
  companyName: "杨氏美容院",
  industry: "beauty",
  brandVision: "让每位女性绽放由内而外的自信之美",
  coreValues: "匠心、真诚、优雅、传承",
  targetMarket: "25-55岁都市女性，追求品质生活的中高端客群",
  brandStory: "杨女士2009年在北京创立杨氏美容院，15年来专注东方女性肌肤护理，融合传统中医养生与现代美容科技，服务超过5000位客户。",
  mascotPhilosophy: "",
  brandColors: {
    primary: "#E8576C",
    secondary: "#F0D5A8",
    accent: "#D4A574",
  },
  logoUrl: "D:/disk/CODEX/vi手册logo/yang_logo_01.png",
};

// ── Scene images (pre-generated by ComfyUI) ─────────────

const sceneImages = [
  { key: "手提袋", path: "D:/disk/CODEX/vi手册logo/yang_scene_01.png" },
  { key: "招牌",   path: "D:/disk/CODEX/vi手册logo/yang_scene_02.png" },
  { key: "名片",   path: "D:/disk/CODEX/vi手册logo/yang_scene_03.png" },
  { key: "海报",   path: "D:/disk/CODEX/vi手册logo/yang_scene_04.png" },
  { key: "产品标签", path: "D:/disk/CODEX/vi手册logo/yang_scene_05.png" },
];

// ── Main ────────────────────────────────────────────────

async function main() {
  console.log("[Yang VI Manual] Starting PPTX generation...");
  
  const industryType = getIndustryType(brandProfile.industry);
  const ik = getIndustryKnowledge(industryType);
  
  console.log(`  Industry: ${ik.label}`);
  console.log(`  Scene modules: ${ik.typicalModules.slice(0, 5).join(", ")}`);
  
  const pptxBuffer = await renderPptxToBuffer({
    companyName: brandProfile.companyName,
    industry: brandProfile.industry,
    brandProfile: brandProfile as any,
    sceneImages: sceneImages.map(s => s.path),
    sceneImageKeys: sceneImages.map(s => s.key),
    logoUrl: brandProfile.logoUrl,
    brandVision: brandProfile.brandVision,
    coreValues: brandProfile.coreValues,
    targetMarket: brandProfile.targetMarket,
    brandStory: brandProfile.brandStory,
  });
  
  const outPath = "D:/disk/CODEX/vi手册logo/Yang_Beauty_Salon_VI_Manual.pptx";
  await writeFile(outPath, pptxBuffer);
  console.log(`\n[OK] VI manual saved: ${outPath}`);
  console.log(`  Size: ${(pptxBuffer.length / 1024).toFixed(1)} KB`);
}

main().catch(e => {
  console.error("[FAIL]", e.message);
  process.exit(1);
});
