/**
 * Brand Brain V1 — Asset Guardian
 *
 * V2: Added ProtectedAssetPolicy for fine-grained asset protection rules.
 *
 * Protects brand assets (Logo, IP mascot) from being modified or
 * regenerated by AI. Enforces the rule that these assets can only be
 * scaled, moved, or positioned — never redrawn, recolored, or reimagined.
 *
 * This guardian sits between the generation pipeline and the AI APIs
 * (DeepSeek, Tongyi Wanxiang) to ensure protected assets are never
 * included in AI prompts or image generation requests.
 */

// ========== Policy ==========

/**
 * Fine-grained permission policy for a protected asset.
 * V2: Replaces simple allow/deny with per-operation control.
 */
export interface ProtectedAssetPolicy {
  /** Allow scaling/resizing */
  allowScale: boolean;
  /** Allow position change */
  allowMove: boolean;
  /** Allow cropping */
  allowCrop: boolean;
  /** Allow opacity/transparency adjustment */
  allowOpacity: boolean;
  /** Allow AI redraw / regeneration */
  allowRedraw: boolean;
  /** Allow color change */
  allowColorChange: boolean;
  /** Allow material/texture change */
  allowMaterialChange: boolean;
}

export interface ProtectedAsset {
  type: "logo" | "mascot" | "brand_color" | "brand_symbol";
  id: string;
  label: string;
  urls: string[];
  /** V2: Per-asset policy */
  policy: ProtectedAssetPolicy;
}

export interface AssetGuardResult {
  safe: boolean;
  warnings: string[];
  protectedAssets: ProtectedAsset[];
  promptModifications: string[];
}

// ========== Default Policies ==========

export const DEFAULT_LOGO_POLICY: ProtectedAssetPolicy = {
  allowScale: true,
  allowMove: true,
  allowCrop: false,
  allowOpacity: true,
  allowRedraw: false,
  allowColorChange: false,
  allowMaterialChange: false,
};

export const DEFAULT_MASCOT_POLICY: ProtectedAssetPolicy = {
  allowScale: true,
  allowMove: true,
  allowCrop: true,
  allowOpacity: true,
  allowRedraw: false,
  allowColorChange: false,
  allowMaterialChange: false,
};

// ========== Policy Validation ==========

/**
 * Check if a requested operation is allowed by the asset's policy.
 */
export function isOperationAllowed(
  operation: keyof ProtectedAssetPolicy,
  asset: ProtectedAsset
): boolean {
  return asset.policy[operation] === true;
}

/**
 * Get a human-readable summary of what a policy allows.
 */
export function summarizePolicy(policy: ProtectedAssetPolicy): string[] {
  const allowed: string[] = [];
  const denied: string[] = [];

  if (policy.allowScale) allowed.push("缩放");
  if (policy.allowMove) allowed.push("移动位置");
  if (policy.allowCrop) allowed.push("裁剪");
  if (policy.allowOpacity) allowed.push("透明度调整");
  if (policy.allowRedraw) denied.push("AI重绘");
  if (policy.allowColorChange) denied.push("改色");
  if (policy.allowMaterialChange) denied.push("改材质");

  const result: string[] = [];
  if (allowed.length > 0) result.push(`允许：${allowed.join("、")}`);
  if (denied.length > 0) result.push(`禁止：${denied.join("、")}`);
  return result;
}

// ========== Prompt Scanning ==========

/**
 * Scan a generation prompt for any mention of protected assets.
 */
export function scanPromptForProtectedAssets(
  prompt: string,
  protectedAssets: ProtectedAsset[]
): { hasProhibitedContent: boolean; modifications: string[] } {
  const modifications: string[] = [];

  for (const asset of protectedAssets) {
    if (prompt.includes(asset.label) || prompt.includes(asset.id)) {
      modifications.push(`⛔ 从提示词中移除「${asset.label}」的引用 — 属于受保护品牌资产`);
    }
  }

  // Check for operations that are denied by policy
  for (const asset of protectedAssets) {
    const policy = asset.policy;

    if (!policy.allowRedraw) {
      const redrawPatterns = [/重绘/i, /redraw/i, /recreate/i, /generate/i];
      for (const p of redrawPatterns) {
        if (p.test(prompt)) {
          modifications.push(`⛔ 禁止AI重绘「${asset.label}」`);
          break;
        }
      }
    }

    if (!policy.allowColorChange) {
      if (/改色/i.test(prompt) || /recolor/i.test(prompt) || /change.*color/i.test(prompt)) {
        modifications.push(`⛔ 禁止修改「${asset.label}」的颜色`);
      }
    }

    if (!policy.allowMaterialChange) {
      if (/材质/i.test(prompt) || /material/i.test(prompt)) {
        modifications.push(`⛔ 禁止修改「${asset.label}」的材质`);
      }
    }
  }

  return {
    hasProhibitedContent: modifications.length > 0,
    modifications,
  };
}

// ========== SVG Safety Section ==========

/**
 * Build the "protected assets" section for an SVG overlay.
 * This is the ONLY allowed usage of logo/IP in generated pages.
 */
export function buildProtectedAssetSection(
  assets: ProtectedAsset[],
  _canvasWidth: number,
  _canvasHeight: number
): string {
  let svg = "";
  for (const asset of assets) {
    const policySummary = summarizePolicy(asset.policy);
    svg += `\n  <!-- PROTECTED ASSET: ${asset.label} (${asset.id}) -->`;
    for (const line of policySummary) {
      svg += `\n  <!-- ${line} -->`;
    }
    svg += `\n  <!-- RULE: Use original image. No AI modification. -->`;
  }
  return svg;
}

// ========== Asset Extraction ==========

/**
 * Extract protected assets from client info with default policies.
 */
export function extractProtectedAssets(clientInfo: {
  logoAssets?: { url: string; fileName?: string }[];
  mascotAssets?: { files: { url: string; fileName?: string }[]; name?: string }[];
}): ProtectedAsset[] {
  const assets: ProtectedAsset[] = [];

  if (clientInfo?.logoAssets?.length) {
    assets.push({
      type: "logo",
      id: "brand-logo",
      label: "品牌Logo",
      urls: clientInfo.logoAssets.map((a) => a.url),
      policy: { ...DEFAULT_LOGO_POLICY },
    });
  }

  if (clientInfo?.mascotAssets?.length) {
    for (let i = 0; i < clientInfo.mascotAssets.length; i++) {
      const mascot = clientInfo.mascotAssets[i];
      assets.push({
        type: "mascot",
        id: `brand-mascot-${i}`,
        label: mascot.name || `IP公仔 ${i + 1}`,
        urls: (mascot.files || []).map((f) => f.url),
        policy: { ...DEFAULT_MASCOT_POLICY },
      });
    }
  }

  return assets;
}

// ========== Negative Prompt ==========

/**
 * Generate the "negative prompt" section to prevent AI from generating
 * content that resembles protected assets.
 */
export function generateAssetProtectionNegativePrompt(
  assets: ProtectedAsset[]
): string {
  const parts: string[] = [];

  for (const asset of assets) {
    if (asset.type === "logo") {
      parts.push("no logo", "no text logo", "no brand mark");
    }
    if (asset.type === "mascot") {
      parts.push("no character", "no mascot", "no cartoon figure", "no illustrated character");
    }
  }

  return parts.join(", ");
}

// ========== Main Guard ==========

/**
 * Main guard function: validate that a generation request is safe.
 */
export function guardGenerationRequest(params: {
  prompt: string;
  clientInfo: any;
}): AssetGuardResult {
  const warnings: string[] = [];
  const protectedAssets = extractProtectedAssets(params.clientInfo);

  const promptCheck = scanPromptForProtectedAssets(params.prompt, protectedAssets);

  if (promptCheck.hasProhibitedContent) {
    warnings.push("提示词中包含了受保护品牌资产的引用或禁止操作");
    warnings.push(...promptCheck.modifications);
  }

  return {
    safe: !promptCheck.hasProhibitedContent,
    warnings,
    protectedAssets,
    promptModifications: promptCheck.modifications,
  };
}
