-- TICKET-122-R14：提示词门拦截记录生产表（只存脱敏展示字段，不含客户提示词全文/密钥）
create table if not exists public.prompt_gate_blocks (
  id bigint generated by default as identity primary key,
  blocked_at timestamptz not null default now(),
  rule_id text not null default '',
  industry_family text not null default '',
  project_code text not null default '',
  scene_role text not null default '',
  prompt_preview text not null default '',
  result text not null default '',
  status text not null default '待核验',
  cost_cny numeric not null default 0,
  prompt_tokens integer not null default 0,
  completion_tokens integer not null default 0,
  model text not null default '',
  finish_reason text,
  geo_inferred_false boolean not null default false,
  source_file text not null default ''
);

create index if not exists idx_prompt_gate_blocks_rule on public.prompt_gate_blocks (rule_id);
create index if not exists idx_prompt_gate_blocks_industry on public.prompt_gate_blocks (industry_family);
create index if not exists idx_prompt_gate_blocks_blocked_at on public.prompt_gate_blocks (blocked_at);
